# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Quick.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from manageData import *


createSLBDB()
u=loadSLBDBClients()
v=loadSLBDBComptes()
lu=setListIdCl()
lv=setListIdCpt()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 50, 221, 461))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.NouveauClient = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.NouveauClient.setContentsMargins(10, 10, 10, 10)
        self.NouveauClient.setHorizontalSpacing(5)
        self.NouveauClient.setVerticalSpacing(10)
        self.NouveauClient.setObjectName("NouveauClient")
        self.identifiantClientLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.identifiantClientLabel.setObjectName("identifiantClientLabel")
        self.NouveauClient.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.identifiantClientLabel)
        self.identifiantClientLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.identifiantClientLineEdit.setEnabled(False)
        self.identifiantClientLineEdit.setAcceptDrops(False)
        self.identifiantClientLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.identifiantClientLineEdit.setObjectName("identifiantClientLineEdit")
        self.NouveauClient.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.identifiantClientLineEdit)
        self.nomLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nomLabel.setObjectName("nomLabel")
        self.NouveauClient.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nomLabel)
        self.nomLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nomLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.nomLineEdit.setObjectName("nomLineEdit")
        self.NouveauClient.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nomLineEdit)
        self.prenomLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.prenomLabel.setObjectName("prenomLabel")
        self.NouveauClient.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.prenomLabel)
        self.prenomLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.prenomLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.prenomLineEdit.setObjectName("prenomLineEdit")
        self.NouveauClient.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.prenomLineEdit)
        self.adresseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.adresseLabel.setObjectName("adresseLabel")
        self.NouveauClient.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.adresseLabel)
        self.adresseLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.adresseLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.adresseLineEdit.setObjectName("adresseLineEdit")
        self.NouveauClient.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.adresseLineEdit)
        self.telephoneLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.telephoneLabel.setObjectName("telephoneLabel")
        self.NouveauClient.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.telephoneLabel)
        self.telephoneLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.telephoneLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.telephoneLineEdit.setObjectName("telephoneLineEdit")
        self.NouveauClient.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.telephoneLineEdit)
        self.nIFLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nIFLabel.setObjectName("nIFLabel")
        self.NouveauClient.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.nIFLabel)
        self.nIFLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nIFLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.nIFLineEdit.setObjectName("nIFLineEdit")
        self.NouveauClient.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.nIFLineEdit)
        self.montantDeCreationLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.montantDeCreationLabel.setObjectName("montantDeCreationLabel")
        self.NouveauClient.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.montantDeCreationLabel)
        self.montantDeCreationLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.montantDeCreationLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.montantDeCreationLineEdit.setObjectName("montantDeCreationLineEdit")
        self.NouveauClient.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.montantDeCreationLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.NouveauClient.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.NouveauClient.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.NewClientID = QtWidgets.QLabel(self.formLayoutWidget)
        self.NewClientID.setStyleSheet("background-color: rgb(152, 216, 255);")
        self.NewClientID.setObjectName("NewClientID")
        self.NouveauClient.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.NewClientID)
        self.NewCompteID = QtWidgets.QLabel(self.formLayoutWidget)
        self.NewCompteID.setStyleSheet("background-color: rgb(152, 216, 255);")
        self.NewCompteID.setObjectName("NewCompteID")
        self.NouveauClient.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.NewCompteID)
        self.CreateClient = QtWidgets.QPushButton(self.formLayoutWidget)
        self.CreateClient.setStyleSheet("background-color: rgb(2, 154, 255);")
        self.CreateClient.setObjectName("CreateClient")
        self.NouveauClient.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.CreateClient)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(460, 50, 160, 281))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.iDCompteLabelDepot = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.iDCompteLabelDepot.setObjectName("iDCompteLabelDepot")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.iDCompteLabelDepot)
        self.iDCompteLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.iDCompteLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.iDCompteLineEdit.setObjectName("iDCompteLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.iDCompteLineEdit)
        self.montantDepotLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.montantDepotLabel.setObjectName("montantDepotLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.montantDepotLabel)
        self.montantDepotLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.montantDepotLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.montantDepotLineEdit.setObjectName("montantDepotLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.montantDepotLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.labelDepot_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.labelDepot_2.setStyleSheet("background-color: rgb(152, 216, 255);")
        self.labelDepot_2.setObjectName("labelDepot_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.labelDepot_2)
        self.Deposer = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.Deposer.setStyleSheet("background-color: rgb(2, 154, 255);")
        self.Deposer.setObjectName("Deposer")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Deposer)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(660, 50, 160, 281))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(10, 10, 10, 10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.iDCompteLabelRetrait = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.iDCompteLabelRetrait.setObjectName("iDCompteLabelRetrait")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.iDCompteLabelRetrait)
        self.iDCompteLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.iDCompteLineEdit_2.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.iDCompteLineEdit_2.setObjectName("iDCompteLineEdit_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.iDCompteLineEdit_2)
        self.montantRetraitLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.montantRetraitLabel.setObjectName("montantRetraitLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.montantRetraitLabel)
        self.montantRetraitLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.montantRetraitLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.montantRetraitLineEdit.setObjectName("montantRetraitLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.montantRetraitLineEdit)
        self.labelRetrait_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.labelRetrait_2.setStyleSheet("background-color: rgb(152, 216, 255);")
        self.labelRetrait_2.setObjectName("labelRetrait_2")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.labelRetrait_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.Retirer = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.Retirer.setStyleSheet("background-color: rgb(2, 154, 255);")
        self.Retirer.setObjectName("Retirer")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Retirer)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(270, 50, 161, 281))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(10, 10, 10, 10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.iDCompte1Label = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.iDCompte1Label.setObjectName("iDCompte1Label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.iDCompte1Label)
        self.iDCompte1LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.iDCompte1LineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.iDCompte1LineEdit.setObjectName("iDCompte1LineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.iDCompte1LineEdit)
        self.iDCompte2Label = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.iDCompte2Label.setObjectName("iDCompte2Label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.iDCompte2Label)
        self.iDCompte2LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.iDCompte2LineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.iDCompte2LineEdit.setObjectName("iDCompte2LineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.iDCompte2LineEdit)
        self.Transferer = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.Transferer.setStyleSheet("background-color: rgb(2, 154, 255);")
        self.Transferer.setObjectName("Transferer")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Transferer)
        self.Transfertlabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Transfertlabel.setStyleSheet("background-color: rgb(152, 216, 255);")
        self.Transfertlabel.setObjectName("Transfertlabel")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.Transfertlabel)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(5, QtWidgets.QFormLayout.SpanningRole, spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem7)
        self.montantTransferLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.montantTransferLabel.setObjectName("montantTransferLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.montantTransferLabel)
        self.montantTransferLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.montantTransferLineEdit.setStyleSheet("background-color: rgb(0, 230, 255);")
        self.montantTransferLineEdit.setObjectName("montantTransferLineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.montantTransferLineEdit)
        self.labelNewClient = QtWidgets.QLabel(self.centralwidget)
        self.labelNewClient.setGeometry(QtCore.QRect(20, 20, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.labelNewClient.setFont(font)
        self.labelNewClient.setObjectName("labelNewClient")
        self.labelDepot = QtWidgets.QLabel(self.centralwidget)
        self.labelDepot.setGeometry(QtCore.QRect(480, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.labelDepot.setFont(font)
        self.labelDepot.setObjectName("labelDepot")
        self.labelRetrait = QtWidgets.QLabel(self.centralwidget)
        self.labelRetrait.setGeometry(QtCore.QRect(660, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.labelRetrait.setFont(font)
        self.labelRetrait.setObjectName("labelRetrait")
        self.labelTranfert = QtWidgets.QLabel(self.centralwidget)
        self.labelTranfert.setGeometry(QtCore.QRect(270, 20, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.labelTranfert.setFont(font)
        self.labelTranfert.setObjectName("labelTranfert")
        self.Statistiques = QtWidgets.QLabel(self.centralwidget)
        self.Statistiques.setGeometry(QtCore.QRect(590, 460, 231, 91))
        self.Statistiques.setObjectName("Statistiques")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(250, 50, 10, 461))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line.setFont(font)
        self.line.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(436, 50, 10, 361))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(630, 50, 10, 361))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.line_3.setLineWidth(4)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.RaffraichirStats = QtWidgets.QPushButton(self.centralwidget)
        self.RaffraichirStats.setGeometry(QtCore.QRect(480, 510, 75, 23))
        self.RaffraichirStats.setStyleSheet("background-color: rgb(2, 154, 255);")
        self.RaffraichirStats.setObjectName("RaffraichirStats")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.CreateClient.clicked.connect(self.creation) #voir methode creation

        #les lignes de codes qui  suivent nettoient les informations rentree une fois le client cree
        self.CreateClient.clicked.connect(self.nomLineEdit.clear)
        self.CreateClient.clicked.connect(self.prenomLineEdit.clear)
        self.CreateClient.clicked.connect(self.nIFLineEdit.clear)
        self.CreateClient.clicked.connect(self.telephoneLineEdit.clear)
        self.CreateClient.clicked.connect(self.adresseLineEdit.clear)
        self.CreateClient.clicked.connect(self.montantDeCreationLineEdit.clear)

        self.Transferer.clicked.connect(self.transf) #pour transferer de l'argent d'un compte a un autre
        #les lignes de codes qui  suivent nettoient les informations rentree une fois le transfert realise
        self.Transferer.clicked.connect(self.iDCompte1LineEdit.clear)
        self.Transferer.clicked.connect(self.iDCompte2LineEdit.clear)
        self.Transferer.clicked.connect(self.montantTransferLineEdit.clear)

        self.Deposer.clicked.connect(self.dep) #pour realiser un depot
        #les lignes de codes qui  suivent nettoient les informations rentree une fois le depot realise
        self.Deposer.clicked.connect(self.iDCompteLineEdit.clear)
        self.Deposer.clicked.connect(self.montantDepotLineEdit.clear)

        self.Retirer.clicked.connect(self.ret) # faire un retrait
        #les lignes de codes qui  suivent nettoient les informations rentree une fois le retrait realise
        self.Retirer.clicked.connect(self.iDCompteLineEdit_2.clear)
        self.Retirer.clicked.connect(self.montantRetraitLineEdit.clear)

        self.RaffraichirStats.clicked.connect(self.stat)
        #self.CreateClient.clicked.connect(self.NewCompteID.lower)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Serge LOUIS BANK"))
        self.identifiantClientLabel.setText(_translate("MainWindow", "Identifiant Client"))
        self.nomLabel.setText(_translate("MainWindow", "Nom"))
        self.prenomLabel.setText(_translate("MainWindow", "Prenom"))
        self.adresseLabel.setText(_translate("MainWindow", "Adresse"))
        self.telephoneLabel.setText(_translate("MainWindow", "Telephone"))
        self.nIFLabel.setText(_translate("MainWindow", "NIF"))
        self.montantDeCreationLabel.setText(_translate("MainWindow", "Montant de Creation"))
        self.NewClientID.setText(_translate("MainWindow", "ID Client :"))
        self.NewCompteID.setText(_translate("MainWindow", "ID Compte :"))
        self.CreateClient.setText(_translate("MainWindow", "Nouveau Client"))
        self.iDCompteLabelDepot.setText(_translate("MainWindow", "IDCompte"))
        self.montantDepotLabel.setText(_translate("MainWindow", "Montant Depot"))
        self.labelDepot_2.setText(_translate("MainWindow", "Statut :"))
        self.Deposer.setText(_translate("MainWindow", "Deposer"))
        self.iDCompteLabelRetrait.setText(_translate("MainWindow", "IDCompte"))
        self.montantRetraitLabel.setText(_translate("MainWindow", "Montant Retrait"))
        self.labelRetrait_2.setText(_translate("MainWindow", "Statut :"))
        self.Retirer.setText(_translate("MainWindow", "Retirer"))
        self.iDCompte1Label.setText(_translate("MainWindow", "ID Compte 1"))
        self.iDCompte2Label.setText(_translate("MainWindow", "ID Compte 2"))
        self.Transferer.setText(_translate("MainWindow", "Transferer"))
        self.Transfertlabel.setText(_translate("MainWindow", "Statut : "))
        self.montantTransferLabel.setText(_translate("MainWindow", "MontantTransfer"))
        self.labelNewClient.setText(_translate("MainWindow", "Nouveau Client"))
        self.labelDepot.setText(_translate("MainWindow", "Depot"))
        self.labelRetrait.setText(_translate("MainWindow", "Retrait"))
        self.labelTranfert.setText(_translate("MainWindow", "Transfert"))
        self.Statistiques.setText(_translate("MainWindow", "Statistiques\nComptes: "+str(len(lv))+"\nClients : "+str(len(lu))))
        self.RaffraichirStats.setText(_translate("MainWindow", "Raffraichir"))
        
    def dep(self):
        global v
        global lv
        a=str(self.iDCompteLineEdit.text())
        b=int(self.montantDepotLineEdit.text())
        if a in lv:
            for el in v:
                if el.idCompte==a:
                    el.deposer(b)
                    saveSLBDBComptes(v)
                    self.labelDepot_2.setText("Depot effectue avec succes!\nNouveau solde :"+str(el.solde))
        else:
            self.labelDepot_2.setText("Le compte n'a pas ete trouve")
            
    def ret(self):
        global v
        global lv
        a=str(self.iDCompteLineEdit_2.text())
        b=int(self.montantRetraitLineEdit.text())
        if a in lv:
            for el in v:
                if el.idCompte==a:
                    el.retirer(b)
                    saveSLBDBComptes(v)
                    self.labelRetrait_2.setText("Retrait effectue avec succes!\nNouveau solde : "+str(el.solde))
        else:
            self.labelRetrait_2.setText("Compte non retrouve")
        
    def transf(self):
        global v
        global lv
        a=str(self.iDCompte1LineEdit.text())
        b=str(self.iDCompte2LineEdit.text())
        c=int(self.montantTransferLineEdit.text())
        if a in lv and b in lv:
            for el in v:
                if el.idCompte==b:
                    i=el
                    for el in v:
                        if el.idCompte==a:
                            el.transferer(i, c)
                            saveSLBDBComptes(v)
                            self.Transfertlabel.setText("Transfere avec succes!\nNouveau Solde : "+str(el.solde))
        else:
            self.Transfertlabel.setText("Echec du transfert: Au moins un des comptes n'existe pas!")
            
            
    def creation(self):
        global u
        global v
        global lu
        global lv
        b=str(self.nomLineEdit.text())
        c=str(self.prenomLineEdit.text())
        d=str(self.adresseLineEdit.text())
        e=str(self.telephoneLineEdit.text())
        f=str(self.nIFLineEdit.text())
        g=int(self.montantDeCreationLineEdit.text())
        
        u, v, lu, lv =createClient(u, v, lu, lv, b, c, d, e, f, g)
        saveListId(lu, lv)
        saveSLBDBClients(u)
        saveSLBDBComptes(v)
        self.NewClientID.setText(lu[len(lu)-1])
        self.NewCompteID.setText(lv[len(lv)-1])

        
    def stat(self):
        self.Statistiques.setText("Statistiques\nComptes: "+str(len(lv))+"\nClients : "+str(len(lu)))
#if __name__ == "__main__":
import sys
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())

